stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
      demands: azureps
    continueOnError: false

    steps:
    
    - task: AzurePowerShell@1
      inputs:
        ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
        ConnectedServiceNameARM: 'Pay-As-You-Go(9638d9af-c663-4e5a-9336-d41b9bafab83)'
        ScriptType: 'InlineScript'
        Inline: 'New-AzureRmResourceGroup -Name RG001 -Location "South Central US"'

    - task: AzurePowerShell@4
      inputs:
        azureSubscription: 'Pay-As-You-Go(9638d9af-c663-4e5a-9336-d41b9bafab83)'
        ScriptType: 'InlineScript'
        Inline: 'Install-Module -Name AzureRM -Force'
        azurePowerShellVersion: 'LatestVersion'