stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
      demands: azureps
    continueOnError: false

    steps:
    - task: AzurePowerShell@1
      inputs:
        ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
        ConnectedServiceNameARM: 'Pay-As-You-Go(9638d9af-c663-4e5a-9336-d41b9bafab83)'
        ScriptType: 'InlineScript'
        Inline: 'New-AzureRmResourceGroup -Name RG02 -Location "South Central US"'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'Install-Module -Name Az -AllowClobber -Scope AllUsers -Force'
        pwsh: true
        

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'Import-Module Az'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'Connect-AzAccount'