stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
      demands: azureps
    continueOnError: false

    steps:
    - task: AzurePowerShell@4
      inputs:
        azureSubscription: 'Pay-As-You-Go(9638d9af-c663-4e5a-9336-d41b9bafab83)'
        ScriptType: 'InlineScript'
        Inline: 'New-AzureRmResourceGroup -Name RG09 -Location "South Central US"'
        azurePowerShellVersion: 'LatestVersion'



    - task: AzurePowerShell@4
      inputs:
        azureSubscription: 'Pay-As-You-Go(9638d9af-c663-4e5a-9336-d41b9bafab83)'
        ScriptType: 'InlineScript'
        Inline: 'New-AzWebApp -RG09 Default-Web-WestUS -Name "ContosoSite" -Location "West US" -AppServicePlan "ContosoServicePlan"'
        azurePowerShellVersion: 'LatestVersion'
        